apiVersion: apps/v1
kind: Deployment
metadata:
  name: tweet-front-client
spec:
  replicas: 2 # Adjust replicas as needed
  selector:
    matchLabels:
      app: tweet-front-client
  template:
    metadata:
      labels:
        app: tweet-front-client
    spec:
      containers:
        - name: tweet-front
          image: devesh121/front-tweet:latest
          ports:
            - containerPort: 5173
          envFrom:
            - configMapRef:
                name: tweet-front-client-config # Create a ConfigMap for .env

---
apiVersion: v1
kind: Service
metadata:
  name: tweet-front-client
spec:
  selector:
    app: tweet-front-client
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
type: LoadBalancer
